### ISSUE TITLE
Is expires_in still working?

### ISSUE THREAD

**Issue by MaximAbramchuck** [rails/actionpack-page_caching#14]
For example

``` ruby
caches_page :home, expires_in: 5.minutes
```

It is not working, or I'm doing something wrong?

**Comment by gioknx** [comment]
I can't get it to work either. Did you find a solution?

**Comment by pixeltrix** [comment]
The `:expires_in` option is for [action caching][1], this gem writes to the filesystem so that the web server serves the content, therefore the only way to expire content is via a [sweeper] or background job.

[1]: https://github.com/rails/actionpack-action_caching
[2]: https://github.com/rails/rails-observers
