### ISSUE TITLE
double slashed home page url creates `.html` page cache file

### ISSUE THREAD

**Issue by njakobsen** [rails/actionpack-page_caching#46]
The double-slashed url does not match the `empty?` or `"/"` condition here https://github.com/rails/actionpack-page_caching/blob/cfcb9521168a82741f6af9e07ebc6dac153224fc/lib/action_controller/caching/pages.rb#L144 so it is interpreted as a legit url, the trailing slash is chomped, and a file is created at `/.html`.

For example `www.my_domain.com//` will page cache to `/public/cache/.html`.

In testing, our NGINX setup serves this file up as an octet-stream, causing it to be downloaded instead of displayed in the browser. To make this even harder to diagnose, the file is hidden on unix-based systems because it begins with a dot.

**Comment by fxn** [comment]
I have add support for this in 5066dc3f64aca2d8152e343fff4ab2a61b4f90ab.

Surprisingly, this part of the code is untested 😱. If you change "/index" with "/foo", the suite is green. I don't konw why is this, but after fighting with the test suite for some time, maybe the reason is that this test suite needs an overhaul.

Anyway, the patch is minimal and I believe correct. I have also checked that series of slashes are already well supported as segment separators elsewhere in non-root paths.

**Comment by fxn** [comment]
@njakobsen we've just published v1.1.1, which includes this fix.
